# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: MIT

cmake_minimum_required(VERSION 3.16)

project(test-natvis LANGUAGES CXX)

set(CMAKE_AUTOUIC ON)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

find_package(QT NAMES Qt6 Qt5 REQUIRED COMPONENTS Core Gui Widgets Network)
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core Gui Widgets Network)

qt_add_executable(test-app
    test-app/main.cpp
    test-app/core_types.h
    test-app/container_types.h
    test-app/variant_types.h
    test-app/network_types.h
    test-app/gui_types.h
    test-app/widgets_types.h
)

qt_add_resources(test-app "assets"
    PREFIX "/"
    BASE "test-app"
    FILES
        test-app/qt.png
        test-app/pass1.json
)

target_link_libraries(test-app
    PRIVATE
        Qt6::Core
        Qt6::Gui
        Qt6::Widgets
        Qt6::Network
)

install(TARGETS test-app LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR})
